#!/bin/sh

set -e
set -x

# Example call: pkgos_insert_include pkgos_func keystone.config
INC=${1}
DST=${2}
SRC="${2}.in"

LINE_NUM=`grep -n "#PKGOS-INCLUDE#" ${SRC} | tail -n 1 | cut -d":" -f1`
NBR_LINES=`cat ${SRC} | wc -l`
cat ${SRC} | head -n $((${LINE_NUM} - 1 )) > ${DST}
cat ${INC} >> ${DST}
tail -n $(($NBR_LINES - $LINE_NUM )) ${SRC} >> ${DST}
